version: 1
formatters:
  simple:
    format: "%(asctime)s-->  %(name)-20s %(levelname)-8s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: scrapper.log

loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console,logfile]
    propagate: yes
root:
  level: DEBUG
  handlers: [console,logfile]